contra_ordenacao_leve_nome = "Contra-Ordenações Leves.ª"
contra_ordenacao_leve_artigo = "Artigo 8.ª"
contra_ordenacao_leves = [
"a) N.º 2 do artigo 10.º, relativo à capacidade",
"b) N.º 3 do artigo 147.º, relativo à competência da IGT",
"c) Artigo 150.º, relativo à obrigação de consulta",
"d) Artigo 152.º, relativo à fixação do mapa de horário",
"e) N.º 2 do artigo 154.º, relativo às condições de isenção de horário de trabalho",
"f) N.º 1 do artigo 170.º, relativo ao regime jurídico do trabalho em regime de disponibilidade",
"g) Artigo 296.º, relativo ao prazo de pagamento dos créditos e compensação"
]

contra_ordenacao_grave_nome = "Contra-Ordenações Graves.ª"
contra_ordenacao_grave_artigo = "Artigo 9.ª"
contra_ordenacao_graves = [
"a) N º2 do artigo 12.º, relativo à forma do contrato de trabalho",
"b) Artigo 13.º, relativo ao conteúdo de trabalho",
"c) Artigo 16.º, relativo à duração do contrato de trabalho por tempo determinado",
"d) N.º 2 do artigo 17. º, relativo à renovação e conversão do contrato de trabalho por tempo determinando",
"e) N.º 3 do artigo 18.º, relativo ao período experimental",
"f) Artigo 21.º, relativo à liberdade de expressão e d opinião",
"g) Artigo 23.º, à reserva da intimidade da vida privada",
"h) N.º 1 do artigo 24.º, relativo à protecção de dados pessoais",
"i) N.ºs 1 e 2 do artigo 25.º, relativo aos testes e exames médicos",
"j) N.ºs 1 e 2 do artigo 36.º, relativo aos princípios gerais na contratação de menores",
"k) Artigo 38.º, relativo aos trabalhos proibidos ou condicionados",
"m) N.ºs 1, 2 e 5 do artigo 40.º, relativo aos exames médicos a menores",
"n) Artigo 41.º, relativo ao salário",
"o) Artigo 42.º, relativo à duração e organização do trabalho",
"p) N.º 1 do artigo 50.º, relativo ao contrato de aprendizagem e contrato",
"q) N.ºs 1, 2, 4, 5 e 7 do artigo 51.º, relativo ao contrato de trabalho a bordo de embarcações",
"r) N.º 1 do artigo 53.º, relativo ao contrato de trabalho no domicílio",
"s) Artigo 58.º, relativo ao conteúdo do contrato de aprendizagem e do contrato de estágio profissional",
"t) Artigo 60.º, relativo à remuneração do aprendiz",
"u) Artigo 64.º, relativo a privacidade do trabalhador em regime de teletrabalho",
"v) N.º 1 do artigo 65.º, relativo ao conteúdo do contrato de comissão de serviço",
"w) N.º 1 do artigo 7.º, relativo aos direitos do trabalhador em caso cessação do contrato de comissão de serviço",
"x) Artigo 71.º, relativo aos deveres da entidade desportiva empregadora",
"y) Artigo 79.º, relativo à alteração das condições de trabalho",
"z) Artigo 81.º, relativo aos deveres da entidade empregadora", 
"aa) N.ºs 3 e 4 do artigo 87.º, relativo às medidas disciplinares",
"bb) N.ºs 1, 3 e 5 do artigo 88.º, relativo ao procedimento disciplinar",
"cc) N.ºs 1 e 4 do artigo 90.º, relativo á entrevista",
"dd) Artigo 91.º, relativo á aplicação da medida disciplinar",
"ee) N.º 1 do artigo 92.º, relativo á graduação da medida disciplinar",
"ff) Artigo 101.º, relativo ao prazo de prescrição e caducidade",
"gg) N.ºs 2 e 3 do artigo 102.º, relativo ao regulamento interno",
"hh) N.º 1 do artigo 103.º, relativo á informação e registo",
"ii) N.ºs 1 e 2 do artigo 109.º, relativo ao dever de informação aos trabalhadores",
"jj) Artigo 114.º, relativo ao dever de comunicação à IGT",
"kk) N.º 1 do artigo 116.º, relativo aos pressupostos matérias de admissibilidade da mobilidade de trabalho",
"ll) Artigo 117.º, relativo aos requisitos formais de admissibilidade de trabalhadores",
"mm) Artigo 127.º, relativo aos requisitos de admissibilidade da mobilidade funcional",
"nn) N.º 1 do artigo 129.º relativo aos requisitos de admissibilidade de mudança para categoria inferior",
"oo) Artigo 132.º, relativo aos requisitos formais de admissibilidade de mudança de local trabalho",
"pp) N.º 1 do artigo 133.º, relativo aos direitos do trabalhador em caso de mobilidade geográfica",
"qq) N.º 2 do artigo 134.º, relativo à mudança de local de trabalho de representante sindical",
"rr) Artigo137.º, relativo à colaboração entre entidades empregadoras",
"ss) N.º 1 do artigo 146.º, relativo à comissão de prevenção de acidentes de trabalho",
"tt) N.ºs 2, 3 e 4 do artigo 148.º, relativo á duração do período normal de trabalho",
"uu) N.º 2 do artigo 149.º, relativo á competência e elaboração de horário de trabalho",
"vv) Artigo 151.º, relativo ao mapa de horário de trabalho",
"ww) N.ºs 1, 2 e 4 do artigo 153.º, relativo à alteração de horário de trabalho",
"xx) Artigo 146.º, relativo ao registo da isenção de horário de trabalho",
"yy) N.ºs 1 e 2 do artigo 161.º, relativo à duração de horário por turnos",
"zz) N.ºs 1 e 2 do artigo 165.º, artigo relativo ao regime jurídico do trabalho em tempo parcial",
"aaa) Artigo 169.º, relativo à admissibilidade do regime de disponibilidade",
"bbb) N.º 1 do artigo 170.º, relativo ao regime jurídico do trabalho em regime de disponibilidade",
"ccc) N. º2 do artigo 172.º, relativo ao regime jurídico do trabalho em alternância",
"ddd) N.º 2 do artigo 177.º, relativo à elaboração do horário de trabalho flexível",
"eee) N.º 1 do artigo 180.º, relativo à redução do trabalho de trabalhador nocturno",
"fff) N. º 2 do artigo 182.º, relativo à remuneração do trabalho nocturno",
"ggg) N.ºs 1 e 3 do artigo 185.º, relativo aos limites de redução do trabalho extraordinário",
"hhh) Artigo 188.º, relativo á remuneração de cada hora de trabalho extraordinário",
"iii) N.ºs 1 do artigo 189.º, relativo ao intervalo para refeição e descanso", 
"jjj) Artigo 190.º, relativo ao repouso diário",
"kkk) N.ºs 1 e 4 do artigo 206.º, relativo ao plano de férias",
"lll) N.º 3 do artigo 213.º, relativo à remuneração e gratificação de férias",
"mmm) N.º 2, 3 e 5 do artigo 216.º, relativo à licença sem remuneração",
"nnn) Artigo 238.º, relativo aos complementos remuneratórios anuais",
"ooo) Artigo 242.º, relativo à forma de pagamento do salário",
"ppp) Artigo 243.º, relativo à forma de pagamento da parte pecuniária do salário",
"qqq) Artigo 245.º, relativo ao período de vencimento do pagamento do salário",
"rrr) Artigo 246.º, relativo ao local de pagamento do salário", 
"sss) N.º 1 e 3 do artigo 247.º, relativo ao documento de pagamento do salário",
"ttt) N.º 2 e 3 do artigo 252.º, relativo à penhorabilidade do salário", 
 "uuu) N.ºs 2 e 4 do artigo 266.º, relativo à apresentação do trabalhador ao empregador",
"vvv) Artigo 275.º, relativo ao certificado de trabalho",
"www) Artigo 275.º, relatório ao aviso prévio no despedimento individual por causas objectivas",
"xxx) Artigo 288.º, relativo aos critérios de preferência na determinação dos trabalhadores a despedir",
"yyy) Artigo 293.º, relativo ao aviso prévio no caso do despedimento colectivo",
"zzz) N.º 4 do artigo 300.º, relativo às consequências da ilicitude do despedimento"
]

contra_ordenacao_muito_grave_nome = "Contra-Ordenações Muito Graves.ª"
contra_ordenacao_muito_grave_artigo = "Artigo 10.ª"
contra_ordenacao_muito_graves = [
"a) Artigo 4.º, relativo ao direito ao trabalho",
"b) N.º 1 do artigo 5.º, relativo á proibição do trabalho obrigatório ou compulsivo",
"c) Artigo 15.º, relativo às causas do contrato de trabalho por tempo determinado",
"d) Artigo 22.º, relativo à integridade física e moral",
"e) Artigo 26.º, relativo aos meios de vigilância à distância",
"f) Artigo 27.º, relativo à confidencialidade de mensagens e de acesso á informação",
"g) N.º 2 do artigo 92.º, relativo á graduação da medida disciplinar",
"h) N.º 1 do artigo 97.º, relativo ao exercício abusivo do poder disciplinar",
"i) Artigo 135.º, relativo ás obrigações geral da entidade empregadora no contexto da segurança, higiene e saúde no trabalho",
"j) Artigo 136.º, relativo às obrigações especificas da entidade empregadora no contexto da segurança higiene e saúde no trabalho",
"k) N.ºs 2 ,3 e 4 do artigo 140.º, relativo aos exames médicos",
"l) Artigo 142.º, relativo ás obrigações imediatas da entidade empregadora",
"m) N.º 1 do artigo 144.º, relativo ao seguro contra risco de acidentes de trabalho e doenças profissionais",
"n) N.º 3 e 4 do artigo 147.º, relativo á competência da IGT",
"o) Artigo 155.º, relativo aos limites de isenção de horário de trabalho",
"p) Artigo 160 .º, relativo à organização de turno",
"p) N.º, 1 do artigo 162 .º, relativo à remuneração do trabalho por turnos",
"r) N.º2 e 3 do artigo 170 .º, relativo ao regime jurídico do trabalho em regime de disponibilidade",
"s) N. 1 e 4 do artigo 173  .º, relativo ao regime do trabalhador e  estudante",
"t) Artigo 181.º, relativo à protecção  de trabalhador nocturno",
"u) N.º 1 artigo 182.º, relativo  à remuneração  do trabalhado nocturno",
"v) N. 1, 2,3, 4 e 7  do artigo 184 .º relativo às condições de trabalho extraordianàrio  ",
"w) Artigo 186 .º, relativo ao descanso compensatório de trabalho extraordianàrio",
"x) N.º 1, e 5 do artigo 187 .º, relativo ao registo extraordianàrio",
"y) N.º 1 do artigo 191 .º, relativo ao direito ao descanso semanal",
"z) Artigo 193 .º, relativo à duração de descanso semanal",
"aa) Artigo 194.º, relativo á remuneração do trabalho",
"bb) Artigo 195.º, relativo ao direito ao descanso complementar semanal",
"cc) Artigo 196.º, relativo às condições e consequências de exercícios de trabalho em dia de descanso semanal no meio dia ou dia de descanso complementar",
"dd) N.º 1 do artigo 197.º, relativo à interrupção do trabalho nos feriados",
"ee) N.º 1 do artigo 198.º, relativo à tolerância de ponto",
"ff) N.º 1 do artigo 199.º, relativo à interrupção da actividade laboral 	na véspera do dia da Familía e do dia do ano novo", 
"gg) N.ºs 1 e 2 do artigo 200.º, relativo à remuneração nos dias de feriados, tolerância de ponto e véspera dia da família e do dia do ano novo",
"hh) N.º 1 do artigo201.º, relativo ao direito a férias",
"ii) Artigo 204.º, relativo à duração de férias",
"jj) N.º, 1 do artigo 209.º, relativo à alteração do período de férias por motivo relativo ao empregador",
"kk) Artigo 211.º, relativo à remuneração de férias havendo suspensão da relação jurídico-laboral",
"LL) Artigo 212.º, relativo à remuneração de férias por cessação da relação jurídico-laboral", 
"mm) N.º 1 do artigo 213.º, relativo à remuneração e gratificação de férias",
"nn) Artigo 214.º, relativo à violação do direito a férias",
"oo) Artigo 218.º, relativo à licença de paternidade",
"pp) N.º 2 artigo 222.º, relativo à remuneração das férias justificadas",
"qq) Artigo 225.º, relativo às faltas para provas escolares",
"rr) N.º 1 do artigo 226.º, relativo ás faltas por acidentes, doença ou assistência",
"ss) Alínea b) do artigo 227.º, relativo ás faltas para actividades culturais ou desportivas",
"tt) Artigo 237.º, relativo à não discriminação salarial",
"uu) N.º 3 do artigo 244.º, relativo ao pagamento da parte não pecuniária",
"vv) N. 1, 2 e 43 do artigo 248.º, relativo aos descontos lícitos",
"ww) Artigo 249.º, relativo aos descontos proibidos",
"xx) N.º 1 do artigo 252.º, relativo à penhorabilidade do salário",
"yy) Artigo 258.º, relativo ao regresso do trabalhador",
"zz) Artigo 272.º, relativo à cessação do impedimento",
"aaa) N.ºs 1 e 2 do artigo 285.º, relativo ao procedimento para o despedimento",
"bbb) Artigo 311.º, relativo á determinação da antiguidade",
"2. Violação do disposto no artigo 1.º do Decreto Presidencial nº. 152/24, de 17 de julho, relativo ao montante do salário mínimo nacional"
]
